import type { CodexProfileArtifactDescriptor, CodexProfileCapture } from "./types.js";

export function createCodexProfileSummary(options: {
    target: CodexProfileArtifactDescriptor;
    capture: CodexProfileCapture;
    promptPatch: string;
    toolsPatch: string;
}): string {
    const { target, capture, promptPatch, toolsPatch } = options;
    const markdownPatch = promptPatch.replace(/[ \t]+$/gmu, (whitespace) =>
        whitespace.replaceAll(" ", "·").replaceAll("\t", "→"),
    );
    const ultraNote =
        target.slug === "gpt-5.6-luna"
            ? "Luna does not receive Rig's Ultra append."
            : "At Ultra effort, Rig appends its separately persisted Ultra instructions after this base prompt; that runtime-only append is not part of the diff below.";
    const officialTools = target.clientTools.map((name) => `\`${name}\``).join(", ");
    const compiledClientPromptSha256 =
        target.slug === "gpt-5.6-sol"
            ? "e9778714d505f3dd04d44db4394024c5fab5bf6554fc9faa3cdf9cf776b63bb9"
            : "78a2fc84e1bffa421d865c1a2ade4185d3d33ef38e6a15157f0ff1a89b7d52ec";
    const markdownToolsPatch = toolsPatch.replace(/[ \t]+$/gmu, (whitespace) =>
        whitespace.replaceAll(" ", "·").replaceAll("\t", "→"),
    );
    const collaborationExtensionNote =
        capture.model.multiAgentVersion === "v2"
            ? "For v2, Rig exposes these additions in a separate top-level `rig` namespace while leaving the reserved `collaboration` definitions unchanged. The `rig` agent tools use plaintext Rig session messages and support cross-model, cross-provider, and cross-region targets; their richer spawn/follow-up schemas include model, provider, and effort controls."
            : "For v1, Rig adds its collaboration and workflow operations as direct functions because that captured client surface has no v2 `collaboration` namespace.";
    const encryptedMessageNote =
        capture.model.multiAgentVersion === "v2"
            ? "- The official v2 `spawn_agent` and `followup_task` message fields remain encrypted: Rig does not inspect them and forwards them to the child as Codex `agent_message` encrypted content."
            : "- The captured v1 surface has no encrypted collaboration fields; Rig's direct agent tools use plaintext Rig session messages.";
    const portabilityNote =
        capture.model.multiAgentVersion === "v2"
            ? "- Rig appends a short runtime portability note: native `collaboration` works through Amazon Bedrock Mantle but its ciphertext is limited to compatible agents in the same provider and region; use `rig` across Codex Cloud/Bedrock, provider instances, models, or regions and for richer controls, and retry rejected native calls without copying ciphertext."
            : "- Rig does not append the v2 namespace portability note to this profile because the captured v1 surface has neither a `collaboration` nor a `rig` namespace.";
    const portableAgentSecurityNote =
        capture.model.multiAgentVersion === "v2"
            ? "- Portable `rig` agent tools reject native-only encrypted fields, mark delegated text as model-authored rather than user authorization, and request Auto review before transferring parent context or model-generated work across an explicit model/provider boundary."
            : "- Rig's direct agent tools use plaintext session messages and mark delegated text as model-authored rather than user authorization.";

    return [
        `# ${target.displayName} profile`,
        "",
        "> This document is generated by `captureCodexGoldens.ts`. It summarizes the intentional Rig deviation and embeds the complete persisted prompt diff for GitHub review.",
        "",
        "## Source",
        "",
        `- Profile: [${target.stem}.ts](./${target.stem}.ts)`,
        `- Official repository: \`${capture.source.repository}\``,
        `- Source revision: \`${capture.source.branch}@${capture.source.commit}\` (${capture.source.commitDate})`,
        `- Source file: \`${capture.source.path}\``,
        `- Model entry: \`${capture.model.slug}\`; tool mode \`${capture.model.toolMode}\`; multi-agent version \`${capture.model.multiAgentVersion}\``,
        `- Capture metadata: [${target.stem}.capture.json](./codex/${target.stem}.capture.json)`,
        "",
        "## Prompt changes",
        "",
        "- Replaces Codex's contradictory leading identity with a model-specific Rig identity and changes the secondary `As Codex` self-reference to `As Rig`.",
        "- Retains every other byte of the official model `base_instructions`, including its communication, tool-use, safety, persistence, and skill guidance.",
        `- Version note: the installed official Codex CLI 0.144.6 compiles an older ${target.displayName} prompt (\`${compiledClientPromptSha256}\`) that differs from this pinned \`main\` source. Among other release-skew changes, \`main\` includes the Destructive Actions section and places the evidence-first objection guidance later. Rig intentionally follows the newer source golden; the gym pins the older client hash separately.`,
        `- ${ultraNote}`,
        "",
        `The official prompt is [${target.stem}.golden.md](./codex/${target.stem}.golden.md), the prompt Rig uses is [${target.stem}.md](./codex/${target.stem}.md), and the standalone diff is [${target.stem}.patch](./codex/${target.stem}.patch).`,
        "",
        "## Tool changes",
        "",
        `- The official \`${capture.model.toolMode}\` surface selects ${officialTools}.`,
        "- Rig now uses the same Code Mode split: raw-text `exec`, function `wait`, direct `request_user_input`, and (for v2) a top-level `collaboration` namespace. Reserved definitions remain close to the official captures, with Rig-specific contracts for `wait` and `request_user_input`; `wait_agent` advertises Rig's five-minute default and steering interruption behavior.",
        "- Removed because Rig does not implement the same client behavior: MCP resource list/read helpers and plugin installation; v2 also omits `send_message` because Rig's existing follow-up operation has different turn-start semantics.",
        `- Added by Rig: secret injection, workflow controls, \`resume_agent\`, richer collaboration variants, and richer execution-result fields. ${collaborationExtensionNote} \`request_user_input\` removes the official Plan-mode-only instruction because Rig deliberately has no separate Plan mode.`,
        encryptedMessageNote,
        portabilityNote,
        portableAgentSecurityNote,
        "- Omits model-facing instructions for `audio()`, because Rig has no audio transcript block, and for `notify()`, because Rig presents notifications as UI progress rather than extra model-visible tool outputs. The Code Mode runtime helpers remain installed.",
        "- Wire-format deviation: official Codex selects Responses Lite and sends `additional_tools` in developer input; Rig currently sends the equivalent custom/function/namespace definitions through the standard Responses `tools` and `instructions` fields.",
        "- Nested tools still execute through Rig's shared AgentContext and permission model. Dynamically configured MCP call tools remain available inside `exec` even though they are absent from this static profile capture.",
        `- Official tools were captured from ${capture.tools.client} CLI ${capture.tools.version}: ${capture.tools.captureMethod}.`,
        `- Tool capture source: ${capture.tools.sourceDescription}. SHA-256: \`${capture.tools.sha256}\`.`,
        "- Prompts were read directly from the source revision above.",
        "",
        `The official tools are [${target.stem}.tools.golden.json](./codex/${target.stem}.tools.golden.json), Rig's computed tools are [${target.stem}.tools.json](./codex/${target.stem}.tools.json), and the standalone diff is [${target.stem}.tools.patch](./codex/${target.stem}.tools.patch).`,
        "",
        "## Full prompt diff",
        "",
        "The embedded diff renders trailing spaces as `·` and trailing tabs as `→`; the linked `.patch` file retains the exact bytes.",
        "",
        "````diff",
        markdownPatch.trimEnd(),
        "````",
        "",
        "## Full tool diff",
        "",
        "````diff",
        markdownToolsPatch.trimEnd(),
        "````",
        "",
    ].join("\n");
}
